### ISSUE TITLE
Creating a corner for Thompson

### ISSUE THREAD

**Issue by chryswoods** [chryswoods/super_project#16]
I've noticed that the current kitchen design doesn't include space for Thompson.

The client included [this photo](https://github.com/chrys-at-home/super_project/blob/main/images/thompson.jpg)

What do you think will be needed?

I believe that we will need space for at least a food and water bowl, which I would be happy to implement.

**Comment by jcwomack** [comment]
Is a litter tray required?

**Comment by chorscroft** [comment]
He also needs a scratching post :)

**Comment by etranos** [comment]
How do you think Thompson will react if a dog appears?

**Comment by umairbinwaheed** [comment]
I think Thompson likes the smell of gas. Let's go for gas!

**Comment by karsafar** [comment]
he might need access to outdoors

**Comment by chryswoods** [comment]
Sorry - we have committed to electric @karsafar

**Comment by f20q** [comment]
How big is he?

**Comment by TLewisProjects** [comment]
It will be nice for Thompson to have a bed

**Comment by TLewisProjects** [comment]
> 
> 
> he might need access to outdoors

A cat flap is a good idea!

**Comment by RobbieMackenzie** [comment]
Thompson's looking a bit funny since I rejected his pull request, perhaps a treat dispenser?

**Comment by chryswoods** [comment]
All the work is done - thanks for all your hard work :-)
