### ISSUE TITLE
Creating a corner for Thompson the cat

### ISSUE THREAD

**Issue by chrys-at-home** [chryswoods/super_project#4]
I've noticed that the current kitchen design doesn't include space for Thompson the cat. The client included [Thompson's Photo](https://github.com/chryswoods/super_project/blob/main/images/thompson.jpg) so I think we should think about this.

What do you think will be needed?

I believe at least a space for a food and water bowl, which I would be happy to implement.

**Comment by chryswoods** [comment]
Good idea - I hadn't got around to thinking about that. What else do you think we need?

**Comment by chryswoods** [comment]
Closing as workshop is over
